### ISSUE TITLE
The dependencies of ReportPortal can't download

### ISSUE THREAD

**Issue by ansonliao** [ngoanh2n/selenide-testng-reportportal-example#1]
Dear @ngoanh2n ,
Thanks for your work on providing this example of Selenide + gradle + reportportal.
After I downloaded the project, and find that the dependencies of the ReportPortal can't download.

After added the repositories setting as below, also some dependencies can't download.
![image](https://user-images.githubusercontent.com/6060224/99387230-89c82700-28cb-11eb-8571-a0cb08134d98.png)

Could you help to advise how to fix it?
Thanks.

**Comment by ngoanh2n** [comment]
Hi @ansonliao 
According to your screenshot, you have added:
- The repository: http://dl.bintray.com/epam/reportportal/ in the `repositories` block
   ```gradle
   maven { url "http://dl.bintray.com/epam/reportportal/" }
   ```
- Dependency: `com.epam.reportportal:agent-java-testng:4.2.0`

This means, Gradle will find `com.epam.reportportal:agent-java-testng:4.2.0` in repository `http://dl.bintray.com/epam/reportportal/`
But you can see that, version 4.2.0 doesn't exist (http://dl.bintray.com/epam/reportportal/com/epam/reportportal/agent-java-testng/)

=> You have found a version which not present in a repository.
Now, you can pick a version at:
- https://mvnrepository.com/artifact/com.epam.reportportal/agent-java-testng?repo=epam-reportportal
- http://dl.bintray.com/epam/reportportal/com/epam/reportportal/agent-java-testng/

**Comment by ansonliao** [comment]
@ngoanh2n 
Thanks for your reply, actually I solved the problem in my machine locally after I found the problem, and thanks for your very detailed reply.
